### ISSUE TITLE
Invitesettings (Newest update)

### ISSUE THREAD

**Issue by therealOri** [ItzPike/DBM-Rawdata-Releases#48]
I updated my Invitesettings command file and my inviteStart event file with the most recent updated files you have on your github and now I get this error every time I run the command. (Never got it before updating)

error >>> `TypeError: Cannot set property '<MY_SERVER_ID_HERE>' of undefined`

Here is my bots log.
```
TypeError: Cannot set property '<MY_SERVER_ID_HERE>' of undefined
?     at eval (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), :16:29)
?     at Object.Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10)
?     at Object.action [as Run Script] (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\actions\run_script.js:287:12)
?     at Object.Actions.invokeActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:502:18)
?     at Object.Actions.preformActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:391:8)
?     at Object.Bot.checkCommand (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:182:12)
?     at Object.Bot.onMessage (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:165:13)
?     at Client.emit (events.js:311:20)
?     at MessageCreateAction.handle (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
?     at Object.module.exports [as MESSAGE_CREATE] (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
?
```

Any fixes or help with this?
I have updated and re installed all the DBM node modules and updated and refreshed all the action, events, etc. folders too and this error still happens after running the invite settings command.

It also seems like none of the other invite manager commands are working...

inviteuser (user) gives me this error >>> `(node:24492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'invitedData' of undefined`

Here is my bots log after running the `inviteuser/inviteplayer` command. 
//(I still git this error even if I keep 'player' as the command name instead of changing it to user)
```
(node:24492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'invitedData' of undefined
    at main (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), <anonymous>:32:42)
    at eval (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), <anonymous>:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

invitetop gives me this error >>>  `(node:20956) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'inviterData' of undefined`

here is my log after running `invitetop`
```
(node:20956) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'inviterData' of undefined
    at main (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), <anonymous>:6:23)
    at eval (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), <anonymous>:53:5)
    at Object.Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10)
    at Object.action [as Run Script] (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\actions\run_script.js:287:12)
    at Object.Actions.invokeActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:502:18)
    at Object.Actions.preformActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:391:8)
    at Object.Bot.checkCommand (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:182:12)
    at Object.Bot.onMessage (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:165:13)
    at Client.emit (events.js:311:20)
    at MessageCreateAction.handle (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
(node:20956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

inviteinfo (link) gives me this error >>> `TypeError: Actions.fetchDatabase is not a function`

Here is my log after running the `inviteinfo (link)` command
```
TypeError: Actions.fetchDatabase is not a function
    at eval (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10), <anonymous>:5:37)
    at Object.Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:344:10)
    at Object.action [as Run Script] (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\actions\run_script.js:287:12)
    at Object.Actions.callNextAction (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:547:18)
    at Object.action [as Store Message Params] (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\actions\store_message_params_MOD.js:228:10)
    at Object.Actions.invokeActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:502:18)
    at Object.Actions.preformActions (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:391:8)
    at Object.Bot.checkCommand (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:182:12)
    at Object.Bot.onMessage (C:\Users\<name>\OneDrive\Desktop\Bot_invitesettings_updated\bot.js:165:13)
    at Client.emit (events.js:311:20)
```

These errors seem to all be stemming from the invitesettings. I had a backup and updated just the inviteStart event and the version check files and no issues. But after updating the invitesettings file...all of this.

Please let me know if you come across anything or have pushed a new update/fix. 
For now..I will not be updating until this is fixed. Hopefully these errors can help you out with fixing this issue.

**Comment by therealOri** [comment]
Update:

After updating ALL of the files to make triple sure of everything being updated and not touching a thing. The commands work.
EXCEPT for `inviteinfo (link)` :/

Here is the error >>> `TypeError: Cannot read property 'playersTracked' of undefined`

And here is my bots log after running the command.

```
TypeError: Cannot read property 'playersTracked' of undefined
    at eval (eval at Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:344:10), <anonymous>:30:48)
    at Object.Actions.eval (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:344:10)
    at Object.action [as Run Script] (C:\Users\<name>\OneDrive\Desktop\Bot\actions\run_script.js:287:12)
    at Object.Actions.callNextAction (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:547:18)
    at Object.action [as Store Message Params] (C:\Users\<name>\OneDrive\Desktop\Bot\actions\store_message_params_MOD.js:228:10)
    at Object.Actions.invokeActions (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:502:18)
    at Object.Actions.preformActions (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:391:8)
    at Object.Bot.checkCommand (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:182:12)
    at Object.Bot.onMessage (C:\Users\<name>\OneDrive\Desktop\Bot\bot.js:165:13)
    at Client.emit (events.js:311:20)
```


ALSO

I get this very annoying message/warning in my logs.
`[Invite Manager] You don't have the GUILD_MEMBERS intent enabled!`

I 100% know it is enabled and have made sure multiple times now that it is indeed enabled and have restarted my bot multiple times And. It. Still. Happens.

Editing this little bit at the top of the file on line `2`  in the inviteStart event makes it stop or work I don't know which one.
```
 // event
    if (globalVars("inviteManagerRanAlready") == null) {
                                               ^
                              //adding 1 "=" to the "==" to make "==="
```

After doing that, everything just breaks and may have something to do with my first comment/above post.


It's either I get that warning non stop even though I have Guild_members intent enabled AND have the `inviteinfo (link)`  command not working.

OR 

Have nothing work at all but have that Guild_members intent warning stop.



Any help would be nice..

**Comment by ItzPike** [comment]
Hello! Thanks for reaching out.

It seems like most of the issue from the first part of the post has been fixed so I will start addressing mainly the second part.

The `GUILD_MEMBERS` intent should be also enabled in DBM aswell. It is the second setting as seen below.
![image](https://user-images.githubusercontent.com/26261307/93376646-e5245d00-f827-11ea-9d3d-f6e31733a07a.png)

Also I do not suggest to change that since it may break the entire system since if that warning isn't printed, that means none of the events are ran aswell which would make the system break.

I see that the inviteinfo patch did fix your issue with that command which is good. I patched it today since I didn't know that was an issue until today when someone had an issue with it.

Please check that you have the above second option checked in DBM and if you have any more issues, please post them here.

**Comment by therealOri** [comment]
Ok, Thank you for the help with this. All of my above issues have been resolved....~~***For now***~~
