### ISSUE TITLE
Latest version gives an error, does not show info.

### ISSUE THREAD

**Issue by master3395** [ItzPike/DBM-Rawdata-Releases#51]
;inviteinfo invitecode
shows the error below.

```
(node:6792) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '267294261941239808' of undefined
    at main (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:90:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

;Inviteplayer <@80357836940382208>

```
(node:6792) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at main (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:43:29)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:27:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

;Invitetop

```
(node:6792) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at main (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:6:39)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:53:5)
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10)
    at Object.action [as Run Script] (/home/dashboard.newstargeted.com/public_html/nt/actions/run_script.js:287:12)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:502:18)
    at Object.Actions.preformActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:391:8)
    at Object.Bot.checkCommand (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:47:15)
    at Object.Bot.onMessage (/home/dashboard.newstargeted.com/public_html/nt/bot.js:165:13)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

These are the versions for the commands over.
(Note Invitesettings does respond, but not sure if it works).

inviteinfo:               // VersionCheck:4
inviteplayer:           // VersionCheck:2
invitesettings:        // VersionCheck:5
invitetop:              // VersionCheck:3

InviteStart Event:  // VersionCheck:11

These are the latest versions that i know works in my bot.
No later version has ever worked in my bot.

inviteinfo:               // VersionCheck:3
inviteplayer:           // VersionCheck:2
invitesettings:        // VersionCheck:4
invitetop:              // VersionCheck:3

InviteStart Event:  // VersionCheck:8

**Comment by ItzPike** [comment]
Contact me further on Discord to coordinate some diagnosis.
